name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Укажите вашу версию .NET

      - name: Restore dependencies
        run: dotnet restore YAAM.Core/YAAM.Core.csproj

      - name: Build project
        run: dotnet build YAAM.Core/YAAM.Core.csproj --configuration Release --no-restore -o ./build_output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: yaam-core-dll
          path: ./build_output/YAAM.Core.dll

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: yaam-core-dll

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
